lanugage: ruby
dist: xenial

addons:
  chrome: stable

services:
  - postgresql

cache:
  - bundler
  - node_modules

notifications:
  email: never

rvm:
  - 2.6.0

before_script:
  - bundle exec chromedriver-update 2.46
  - psql -c 'create database travis_ci_test;' -U postgres
  - cp config/database.yml.travis config/database.yml
  - ln -s /usr/lib/chromium-browser/chromedriver ~/bin/chromedriver

install:
  - bundle install --jobs=3 --retry=3
  - npm install

script:
  - bundle exec rspec
