lanugage: ruby

services:
  - postgresql

cache:
  - bundler
  - node_modules

notifications:
  email: never

rvm:
  - 2.5.1

before_install:
 - sudo apt-get update
 - sudo apt-get install chromium-chromedriver

before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - cp config/database.yml.travis config/database.yml
  - "export PATH=$PATH:/usr/lib/chromium-browser/"
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3

install:
  - bundle install --jobs=3 --retry=3
  - npm install

script:
  - bundle exec rspec
