version: '3'

networks:
  spaziergang-net:

services:
  db:
    image: postgres:10.5
    restart: always
    volumes:
      - ./postgres-vol:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: user
    networks:
      spaziergang-net:
        aliases:
          - db
  web:
    build: .
    volumes:
      - ./assets-vol:/app/public/assets
    depends_on:
      - db
    environment:
      RAILS_ENV: production
      SECRET_KEY_BASE: 1ce948cf5b5597f0acab869e9cd42058e0a2a0f5f4d5ae9c1144e1ff4201de85f3ebf4f25760f6b1
      DATABASE_URL: postgresql://user:password@db:5432/user?pool=5&timeout=5000
      SENTRY_DSN: "https://secretkey@sentry.server/projectidx"
    networks:
      spaziergang-net:
        aliases:
          - web

  nginx:
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - web
    volumes:
      - ./assets-vol:/var/www/spaziergang_creator/assets
    networks:
      spaziergang-net:
        aliases:
          - nginx
