version: '2'

networks:
  spaziergang-net:

services:
  db:
    image: postgres:10.5
    restart: unless-stopped
    volumes:
      - ./postgres-vol:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    networks:
      spaziergang-net:
        aliases:
          - db
  web:
    restart: unless-stopped
    build: .
    volumes:
      - ./assets-vol:/app/public/assets
    depends_on:
      - db
    environment:
      HOME_NAME: ${HOME_NAME}
      WALK_APP_URL: ${WALK_APP_URL}
      CONTACT_EMAIL: ${CONTACT_EMAIL}
      RAILS_ENV: production
      SECRET_KEY_BASE: ${SECRET_KEY_BASE}
      DATABASE_URL: "postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}?pool=5&timeout=5000"
      SENTRY_DSN: ${SENTRY_DSN}
      MATOMO_URL: ${MATOMO_URL}
      MATOMO_ID: ${MATOMO_ID}
    networks:
      spaziergang-net:
        aliases:
          - web

  nginx:
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - web
    volumes:
      - ./assets-vol:/var/www/spaziergang_creator/assets
    networks:
      spaziergang-net:
        aliases:
          - nginx
